# docker compose is only used in dev mode to setup local db and prisma service
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.8
    restart: always
    ports:
      - '4477:4477'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4477
        databases:
          default:
            connector: mysql
            host: mysql-db
            port: 3306
            user: root
            password: prisma
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~


# PG SQL Setup
# version: '3'
# services:
#   prisma:
#     image: prismagraphql/prisma:1.28.5
#     restart: always
#     ports:
#     - "4477:4477"
#     environment:
#       PRISMA_CONFIG: |
#         port: 4477
#         # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
#         managementApiSecret: aid-tmcc
#         databases:
#           default:
#             connector: postgres
#             host: postgres-db
#             port: 5432
#             user: prisma
#             password: postgresPass
#             migrations: true
#   postgres-db:
#     image: postgres:10.5
#     restart: on-failure
#     ports:
#       - '5435:5432'
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: postgresPass
#     volumes:
#       - postgres:/var/lib/postgresql/data
# volumes:
#   postgres: ~
